### PR TITLE
Learn bug fixes

### LINKED ISSUE #168: Bug fixes before Learn
For develop branch:

- [x] role variable in activityManager is not defined: delete the check for "if (role != undefined)" in distributeStamp (see backup branch for how it should look)
- [x] all commands except stamp ones are disabled - make sure all commands are enabled

For backup branch:

- [ ] comment out or fix issues with logger trying to access null objects

For both but not urgent:

- [x] you get an error message every time you run !init-bot and select "No" when it asks if you have more verification roles
- [ ] activity voice channel always visible to hackers even when lo-tech solution is on

### PR DESCRIPTION
**Pull request by JPGarCar**
Closes #168 by fixing the found bugs.

### CODE REVIEW

File: classes/bot-guild.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 const { Collection, Snowflake, Guild, TextChannel, Role, GuildAuditLogs, Message, MessageEmbed } = require('discord.js');
 const { CommandoClient, CommandoGuild } = require('discord.js-commando');
 const winston = require('winston');
+const { cli } = require('winston/lib/winston/config');
```
Comment (JPGarCar) [inline classes/bot-guild.js:4]: Not needed!
